export const RCMKnowledgeBase = {
  denialCodes: {
    CO: [
      {code: 'CO-4', name: 'Modifier Inconsistency', description: 'Missing/incorrect modifier on CPT code', fix: 'Review coding guidelines, correct modifier, resubmit'},
      {code: 'CO-11', name: 'Diagnosis/Procedure Mismatch', description: 'Diagnosis does not match procedure', fix: 'Verify medical records support link, correct codes or appeal'},
      {code: 'CO-22', name: 'Coordination of Benefits Issue', description: 'May be covered by another insurance', fix: 'Verify primary payer'},
      {code: 'CO-29', name: 'Timely Filing Expired', description: 'Submitted after deadline', fix: 'Appeal with proof of original timely submission'},
      {code: 'CO-50', name: 'Not Medically Necessary', description: 'Service not considered medically necessary', fix: 'Appeal with doctor letter of medical necessity, supporting records'},
      {code: 'CO-96', name: 'Non-Covered Charge', description: 'Service not covered by plan', fix: 'Verify benefits, if not covered obtain signed waiver before rendering'},
      {code: 'CO-97', name: 'Bundled Service', description: 'Service included in payment for another', fix: 'Review NCCI bundling edits'},
      {code: 'CO-109', name: 'Incorrect Payer', description: 'Claim sent to wrong payer', fix: 'Identify correct payer and resubmit'},
      {code: 'CO-119', name: 'Benefit Maximum Reached', description: 'Plan benefit maximum has been reached', fix: 'Verify benefits, write off contractual adjustment'},
      {code: 'CO-150', name: 'Level of Service Not Supported', description: 'Documentation does not justify level billed', fix: 'Ensure documentation justifies level billed'},
      {code: 'CO-151', name: 'Days/Units Limitation', description: 'Exceeded plan limits for days or units', fix: 'Check plan limits, appeal with supporting documentation'},
      {code: 'CO-167', name: 'Diagnosis Not Covered', description: 'Diagnosis code not covered by plan', fix: 'Verify ICD codes for accuracy'},
      {code: 'CO-185', name: 'Provider Not Eligible', description: 'Provider is not eligible/credentialed', fix: 'Verify credentialing status'},
      {code: 'CO-197', name: 'Precertification/Authorization Absent', description: 'Required authorization not obtained', fix: 'Check retroauth, submit retroactive authorization'},
      {code: 'CO-204', name: 'Service Not Under Benefit Plan', description: 'Service not covered under current benefit plan', fix: 'Verify plan benefits, appeal if misinterpretation'},
      {code: 'CO-205', name: 'Pharmacy/DME Dispensing Limit Reached', description: 'Dispensing limit for pharmacy or DME reached', fix: 'Check plan limits'},
      {code: 'CO-206', name: 'Transcription/Lab Not Covered In-House', description: 'Transcription or lab service not covered when done in-house', fix: 'Verify coverage policy'},
    ],
    PR: [
      {code: 'PR-1', name: 'Deductible Amount', description: 'Patient has not met deductible', fix: 'Bill patient, explain how deductibles work'},
      {code: 'PR-2', name: 'Coinsurance Amount', description: 'Patient percentage share of costs', fix: 'Bill patient coinsurance amount'},
      {code: 'PR-3', name: 'Copayment Amount', description: 'Fixed copay due from patient', fix: 'Collect fixed copay amount'},
      {code: 'PR-5', name: 'Covered Under Different Plan', description: 'Service covered under a different plan', fix: 'Coordinate benefits'},
      {code: 'PR-6', name: 'Non-Covered Service', description: 'Service not covered - patient responsibility', fix: 'Bill patient, must have signed ABN for Medicare'},
      {code: 'PR-15', name: 'No Prior Authorization', description: 'Authorization not obtained prior to service', fix: 'Try retroauth, appeal if urgent/emergent'},
      {code: 'PR-16', name: 'Missing Information', description: 'Claim missing required information', fix: 'Correct errors and resubmit'},
      {code: 'PR-24', name: 'Capitation Coverage', description: 'Service covered under capitation', fix: 'No additional billing allowed'},
      {code: 'PR-33', name: 'Patient Not Identified', description: 'Patient information incorrect or missing', fix: 'Verify correct patient information'},
      {code: 'PR-40', name: 'Not Emergent/Urgent', description: 'Service determined not emergent or urgent', fix: 'Appeal with ED records if truly emergent'},
      {code: 'PR-57', name: 'Eligibility/Residency Not Met', description: 'Patient eligibility or residency requirements not met', fix: 'Verify eligibility, assist with enrollment'},
    ],
    N: [
      {code: 'N1', description: 'Charges exceed fee schedule'},
      {code: 'N18', description: 'Missing pre-op photos'},
      {code: 'N25', description: 'Missing provider identifier'},
      {code: 'N30', description: 'Patient ineligible'},
      {code: 'N34', description: 'Missing CLIA certification'},
      {code: 'N38', description: 'Missing occurrence codes'},
      {code: 'N57', description: 'Missing revenue codes'},
      {code: 'N61', description: 'Rebill services on separate claims'},
      {code: 'N77', description: 'Missing designated provider number'},
    ],
  },
  billingScenarios: [
    {
      scenario: 'Patient Calls About a Bill',
      protocol: [
        'Verify identity (name, DOB, last 4 SSN)',
        'Acknowledge concern',
        'Look up account',
        'Break down insurance paid vs patient owes',
        'Offer payment options',
      ],
    },
    {
      scenario: 'Denied Claim',
      protocol: [
        'Pull claim',
        'Identify denial code',
        'Explain in plain language',
        'Determine type (billing/coverage/medical necessity)',
        'Explain next steps',
        'Fix or appeal',
      ],
    },
    {
      scenario: 'Incorrect Charges',
      protocol: [
        'Never argue',
        'Investigate',
        'If error, apologize and correct',
        'If correct, explain each charge',
        'Offer itemized bill',
      ],
    },
    {
      scenario: 'Out-of-Network Issues',
      protocol: [
        'Check No Surprises Act protections (emergency, ancillary at in-network facilities)',
        'Explain OON vs INN differences',
        'Offer superbill for patient to file',
      ],
    },
    {
      scenario: 'Deductible Questions',
      protocol: [
        'Explain: Your deductible is the amount you pay each year before insurance starts sharing costs',
        'Tell remaining deductible amount',
        'Explain coinsurance kicks in after deductible',
        'Once OOP max met, insurance pays 100%',
      ],
    },
  ],
  rcmWorkflow: [
    {step: 1, name: 'Patient Registration', description: 'Collect demographics, insurance info, signatures'},
    {step: 2, name: 'Insurance Verification & Eligibility', description: 'Confirm active coverage, benefits, auth requirements, network status, COB'},
    {step: 3, name: 'Charge Capture', description: 'Document all services, ensure charges match documentation'},
    {step: 4, name: 'Medical Coding', description: 'Translate to CPT, ICD-10, HCPCS codes with modifiers'},
    {step: 5, name: 'Claim Submission', description: 'Send electronically (837) or paper (CMS-1500/UB-04), use clearinghouse'},
    {step: 6, name: 'Payment Posting', description: 'Post ERA/EOB payments, apply adjustments, transfer patient responsibility'},
    {step: 7, name: 'Denial Management', description: 'Identify reason, categorize (admin/clinical/coverage), correct or appeal'},
    {step: 8, name: 'Patient Collections', description: 'Generate statements, handle inquiries, offer payment plans'},
  ],
  kpis: {
    daysInAR: {target: '30-40 days', description: 'Days in Accounts Receivable'},
    cleanClaimRate: {target: '95%+', description: 'Percentage of claims paid on first submission'},
    denialRate: {target: '<5%', description: 'Percentage of claims denied'},
    netCollectionRate: {target: '95%+', description: 'Percentage of allowable charges collected'},
    firstPassResolution: {target: 'High', description: 'Issues resolved without escalation'},
  },
  hipaaCompliance: {
    whatCanBeSaid: ['Your name and org', 'Calling regarding your account', 'Callback number', 'General purpose'],
    whatCannotBeSaid: ['Specific dollar amounts on voicemail', 'Clinical info', 'Diagnoses', 'Full SSNs', 'Patient name + sensitive details'],
    voicemailRules: 'Generic only, never leave details about balances or services, verify phone number first',
    identityVerification: 'Full name, DOB, last 4 SSN before discussing any PHI',
    minimumNecessaryStandard: 'Only access/disclose minimum PHI needed',
    canDiscussWith: ['Patient always', 'Legal guardian (with proof)', 'Authorized person (with signed authorization)'],
  },
  insuranceTypes: {
    HMO: {network: 'Strict', referrals: 'Needed from PCP', outOfNetwork: 'Emergency only', premium: 'Lower'},
    PPO: {network: 'Large', referrals: 'No referrals needed', outOfNetwork: 'Covered but higher cost', premium: 'Higher'},
    EPO: {network: 'Network only', referrals: 'No referrals needed', outOfNetwork: 'Emergency/urgent only', premium: 'Moderate'},
    POS: {network: 'Hybrid', referrals: 'Referrals from PCP', outOfNetwork: 'Covered but higher cost', premium: 'Moderate'},
    HDHP: {network: 'Varies', referrals: 'Varies', outOfNetwork: 'Varies', premium: 'Lower', notes: 'High deductible ($3K-$8K+), often paired with HSA'},
    Medicare: {parts: ['Part A: Hospital', 'Part B: Outpatient', 'Part C: Advantage', 'Part D: Drugs'], rules: 'Strict rules, no balance billing, 12-month timely filing'},
    Medicaid: {description: 'State-administered, payer of last resort, retroactive coverage possible'},
  },
  appealProcess: {
    steps: [
      'Step 1: Analyze denial (CARC + RARC codes)',
      'Step 2: Gather documentation (denial letter, claim details, medical records, letter of medical necessity, clinical studies, policy language)',
      'Step 3: Write appeal letter (patient info, claim number, denial date, why incorrect, supporting evidence)',
      'Step 4: Submit via certified mail, keep copies',
    ],
    timelines: {
      standardPreService: '30 days',
      standardPostService: '60 days',
      expeditedUrgent: '72 hours',
      externalReview: '60 days',
    },
    levels: [
      {level: 1, name: 'Internal Appeal', timeline: '180 days from denial'},
      {level: 2, name: 'Physician Peer-to-Peer', timeline: 'Varies'},
      {level: 3, name: 'External Review', timeline: '60 days', notes: 'Binding, no cost to patient'},
      {level: 4, name: 'Independent Medical Review', timeline: 'Varies'},
    ],
  },
  payerSpecific: {
    UnitedHealthcare: {filingDeadline: '90-180 days', appealDeadline: '180 days', notes: 'Optum for payment integrity, Gold Card program for waived auth'},
    Aetna: {filingDeadline: '90-120 days', appealDeadline: '180 days', notes: 'Clinical Policy Bulletins (CPBs) - cite in appeals'},
    Cigna: {filingDeadline: '90-365 days', appealDeadline: '180 days', notes: 'Cigna+Oscar plans have different networks'},
    Humana: {filingDeadline: '365 days (Medicare)', appealDeadline: '60 days (Medicare Advantage)', notes: 'HCC coding focus'},
    BCBS: {filingDeadline: 'Varies by state', appealDeadline: 'Varies by state', notes: 'Each is independent, use Availity for multi-plan management'},
    Medicare: {filingDeadline: '12 months', appealLevels: 5, notes: 'No balance billing, MUE/NCCI edits strict'},
    Medicaid: {filingDeadline: 'Varies by state', notes: 'Payer of last resort, verify eligibility every visit'},
  },
  scripts: {
    upsetPatient: 'I hear how frustrated you are, and I want to help. Let me look into exactly what happened with this charge so I can explain it clearly.',
    explainingDeductible: 'Think of your deductible like a yearly threshold. Your plan requires you to pay the first $X each year before insurance starts helping. Right now you\'ve met $Y of $Z deductible.',
    adminDenial: 'Your claim was denied because of a missing piece of information. This is something we can fix on our end - we just need to resubmit with the correct info.',
    medicalNecessityDenial: 'The insurance company needs more information to show this service was medically necessary. Your doctor can submit additional clinical records.',
    paymentPlan: 'We offer flexible payment plans with no interest and no credit check. You can choose a monthly amount that works for your budget.',
    billingError: 'I sincerely apologize for the error. You\'re right - this charge was incorrect. I\'ve corrected it in our system.',
  },
  paymentPlans: {
    standardPlans: [
      {term: 'Short-term', duration: '3 months'},
      {term: 'Standard', duration: '6 months'},
      {term: 'Extended', duration: '12 months'},
      {term: 'Custom', duration: 'Negotiable'},
    ],
    charityCare: 'Free/discounted care for qualifying low-income patients based on Federal Poverty Guidelines',
    slidingFeeScales: [
      {incomeLevel: '100% FPG', discount: 'Free'},
      {incomeLevel: '150% FPG', discount: 'Sliding scale'},
      {incomeLevel: '200% FPG', discount: 'Partial'},
    ],
    discounts: ['Prompt pay', 'Self-pay', 'Hardship', 'Cash'],
  },
  glossary: [
    {term: 'Pre-Authorization', definition: 'Approval from insurance before service'},
    {term: 'Copay', definition: 'Fixed dollar amount at time of service'},
    {term: 'Coinsurance', definition: 'Percentage of costs after deductible'},
    {term: 'Deductible', definition: 'Amount paid before insurance shares costs'},
    {term: 'Out-of-Pocket Maximum', definition: 'Most patient pays in a year'},
    {term: 'Allowed Amount', definition: 'Max insurance will pay for service'},
    {term: 'Write-Off', definition: 'Amount provider deducts per contract'},
    {term: 'EOB', definition: 'Explanation of Benefits from insurance (not a bill)'},
    {term: 'ERA', definition: 'Electronic Remittance Advice (835 format)'},
    {term: '837', definition: 'Electronic claim file format'},
    {term: 'CMS-1500', definition: 'Professional claim form'},
    {term: 'UB-04', definition: 'Institutional/hospital claim form'},
    {term: 'CPT', definition: 'Procedure codes (e.g., 99213)'},
    {term: 'ICD-10', definition: 'Diagnosis codes (e.g., E11.9)'},
    {term: 'HCPCS', definition: 'Codes for supplies, drugs, equipment'},
    {term: 'Modifier', definition: 'Two-digit code for additional info'},
    {term: 'DRG', definition: 'Inpatient payment classification'},
    {term: 'NPI', definition: 'National Provider Identifier (10-digit)'},
    {term: 'TIN', definition: 'Taxpayer ID / EIN'},
    {term: 'Clearinghouse', definition: 'Intermediary that scrubs and forwards claims'},
    {term: 'CARC', definition: 'Claim Adjustment Reason Code - uses prefixes (CO, PR, PI, OA, N-codes)'},
    {term: 'RARC', definition: 'Remittance Advice Remark Code - supplementary info on remittance'},
    {term: 'ABN', definition: 'Advance Beneficiary Notice - Medicare waiver for non-covered services'},
  ],
};